# Generated by Django 6.0.6 on 2026-06-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Product name, e.g., USDA Choice Ribeye', max_length=255)),
                ('sku', models.CharField(help_text='Stock Keeping Unit number', max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Proteins', 'Proteins'), ('Dairy', 'Dairy'), ('Produce', 'Produce'), ('Beverages', 'Beverages'), ('Dry Goods', 'Dry Goods'), ('Disposables', 'Disposables')], help_text='Food department or supply class', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Unit purchase cost from supplier', max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=2, default=0.0, help_text='Current stock quantity (allows fractional counting)', max_digits=8)),
                ('unit', models.CharField(choices=[('Cases', 'Cases'), ('Lbs', 'Lbs'), ('Gallons', 'Gallons'), ('Bottles', 'Bottles'), ('Packs', 'Packs'), ('Ounces', 'Ounces'), ('Units', 'Units')], default='Cases', help_text='Unit of measurement (e.g., Lbs, Gallons)', max_length=30)),
                ('min_stock', models.DecimalField(decimal_places=2, default=5.0, help_text='Low stock alert trigger amount', max_digits=8)),
                ('storage_location', models.CharField(choices=[('Walk-In Cooler', 'Walk-In Cooler'), ('Walk-In Freezer', 'Walk-In Freezer'), ('Dry Pantry', 'Dry Pantry'), ('Bar Shelf', 'Bar Shelf'), ('Line Station', 'Line Station')], default='Dry Pantry', help_text='Where the item is physically stored', max_length=50)),
                ('supplier', models.CharField(blank=True, help_text='Vendor/supplier name (e.g., Sysco, US Foods)', max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Automatically track last modification')),
            ],
        ),
    ]
