# Generated by Django 6.0.6 on 2026-06-22 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorysystem', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_modified_by',
            field=models.ForeignKey(blank=True, help_text='The user account that last managed or adjusted this stock item', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage_location',
            field=models.CharField(choices=[('Walk-In Cooler', 'Walk-In Cooler'), ('Walk-In Freezer', 'Walk-In Freezer'), ('Dry Pantry', 'Dry Pantry'), ('Bar Shelf', 'Bar Shelf'), ('Line Station', 'Line Station'), ('Bar Walk-in Cooler', 'Bar Walk-in Cooler')], default='Dry Pantry', help_text='Where the item is physically stored', max_length=50),
        ),
        migrations.CreateModel(
            name='WasteLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_wasted', models.DecimalField(decimal_places=3, help_text="Quantity wasted, in the product's default unit of measurement", max_digits=3)),
                ('reason', models.CharField(choices=[('Spoilage', 'Spoilage / Expired'), ('Prep Error', 'Ktichen Prep Error'), ('Dropped', 'Dropped / Damaged '), ('Customer Return', 'Customer Return / Complaint'), ('Over-Portioning', 'Over-Portioning / Line Waste')], help_text='Why was this product thrown away?', max_length=50)),
                ('notes', models.TextField(blank=True, help_text="Optional context (e.g. 'not prepped to spec', 'spoiled / burnt)", null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of exactly when waste occurred')),
                ('logged_by', models.ForeignKey(help_text='Staff member who recorded the waste', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(help_text='The inventory item that was wasted', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_logs', to='inventorysystem.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
